# Generated by Django 6.0.6 on 2026-06-15 02:44

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('color', models.CharField(default='#3498db', help_text='分类标签颜色，如 #3498db', max_length=7, verbose_name='颜色')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '新闻分类',
                'verbose_name_plural': '新闻分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='列表页简介')),
            ],
            options={
                'verbose_name': '新闻列表页',
                'verbose_name_plural': '新闻列表页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='发布日期')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='简介')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 3), ('html_content', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '支持HTML5 video标签或第三方视频平台嵌入代码', 'icon': 'media', 'label': '视频嵌入'}), 4: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '支持原始HTML，用于复杂内容展示', 'icon': 'code', 'label': 'HTML内容'})})),
                ('allow_comments', models.BooleanField(default=True, verbose_name='允许评论')),
                ('allow_sharing', models.BooleanField(default=True, verbose_name='允许分享')),
                ('allow_likes', models.BooleanField(default=True, verbose_name='允许点赞')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='关键词')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='封面图片')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newscategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '新闻文章',
                'verbose_name_plural': '新闻文章',
                'ordering': ['-publish_date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='news.newsarticle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.NewsTag', to='taggit.Tag', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='员工ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户配置文件',
                'verbose_name_plural': '用户配置文件',
            },
        ),
        migrations.CreateModel(
            name='ArticleReadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('read_duration', models.IntegerField(default=0, verbose_name='阅读时长(秒)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否读完')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='news.newsarticle')),
            ],
            options={
                'verbose_name': '阅读记录',
                'verbose_name_plural': '阅读记录',
                'indexes': [models.Index(fields=['article', 'user'], name='news_articl_article_58a5bf_idx'), models.Index(fields=['read_at'], name='news_articl_read_at_3ee2ac_idx')],
                'unique_together': {('article', 'user', 'read_at')},
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.newsarticle')),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'user'], name='news_articl_article_cb6895_idx')],
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否审核通过')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.articlecomment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsarticle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'is_approved'], name='news_articl_article_30a382_idx')],
            },
        ),
    ]
