# Generated by Django 6.0.6 on 2026-06-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_duplicate_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='URL标识'),
        ),
    ]
