# Generated by Django 6.0.6 on 2026-06-17 03:21

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_follow_subscribe_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlereadrecord',
            unique_together={('article', 'user')},
        ),
        migrations.AlterField(
            model_name='articlereadrecord',
            name='read_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='阅读时间'),
        ),
    ]
